export default [{
  heading: 'footer.getStarted',
  links: [{
    label: 'footer.wallet',
    to: 'downloads',
  }, {
    label: 'footer.buy',
    buy: true,
  }, {
    label: 'footer.infographics',
    to: 'infographics',
  }, {
    label: 'footer.team',
    href: 'https://blog.skycoin.net/statement/skycoin-team/',
  }, {
    label: 'footer.subscribe',
    to: 'mailing-list',
  }, {
    label: 'footer.market',
    to: 'markets',
  }, {
    label: 'footer.bitcoinTalks',
    href: 'https://bitcointalk.org/index.php?topic=380441',
  }],
}, {
  heading: 'footer.explore',
  links: [{
    label: 'footer.blog',
    href: 'http://blog.skycoin.net',
  }, {
    label: 'footer.whitepapers',
    to: '/whitepapers',
  }, {
    label: 'footer.blockchain',
    href: 'http://explorer.skycoin.net/blocks',
  }, {
    label: 'footer.distribution',
    to: 'distribution',
  }, {
    label: 'footer.roadmap',
    to: '/roadmap',
  }, {
    label: 'footer.skyMessenger',
    href: 'http://messenger.skycoin.net/',
  }, {
    label: 'footer.cxPlayground',
    href: 'http://cx.skycoin.net/',
  }],
}, {
  heading: 'footer.community',
  links: [{
    label: 'footer.reddit',
    href: 'https://www.reddit.com/r/SkycoinProject',
  }, {
    label: 'footer.twitter',
    href: 'https://twitter.com/skycoinproject',
  }, {
    label: 'footer.github',
    href: 'https://github.com/skycoin/skycoin',
  }, {
    label: 'footer.telegram',
    href: 'https://t.me/Skycoin',
  }, {
    label: 'footer.slack',
    href: 'http://skycoin.herokuapp.com/',
  }, {
    label: 'footer.discord',
    href: 'https://discord.gg/EgBenrW',
  }, {
    label: 'footer.facebook',
    href: 'https://www.facebook.com/skycoinproject',
  }, {
    label: 'footer.instagram',
    href: 'https://www.instagram.com/skycoinproject/',
  }],
}];
